
title: jCliff.io
email: joshua.clifford91@gmail.com
description: >-
  jCliff.io is a personal/blog site for Josh Clifford.
baseurl: "/"
url: "https://jcliff.io"
permalink: /blog/:year/:month/:day/:title
twitter_username: jcliffio
github_username:  jcliffio
google_analytics: "UA-56671484-1"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed