
title: jcliff.io
author: Josh Clifford
email: joshua.clifford91@gmail.com
description: >-
  I'm just a dude, playing a dude, disguised as another dude.
baseurl: "/"
url: "https://jcliff.io"
permalink: /blog/:year/:month/:day/:title
twitter_username: jcliffio
github_username:  jcliffio
google_analytics: "UA-56671484-1"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed